#!/bin/bash
# This simplifies githubbing

echo "Enter filename:"
read varname

# Make the file executable
chmod +x "$varname"

# Add all changes
git add .

# Prompt for a custom commit message
echo "Enter commit message:"
read commit_message

# Commit changes with the custom message
git commit -m "Implementation of $varname: $commit_message"

# Push changes to the remote repository
git push
